# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile_tn.yml
  tasks:

    - name: Create ip pool
      nsxt_ip_pools:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.display_name}}"
        subnets: "{{item.subnets}}"
        state: present
      with_items:
        - "{{ip_pools}}"

    - name: Create transport zone
      nsxt_transport_zones:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        resource_type: "TransportZone"
        display_name: "{{item.display_name}}"
        description: "NSX configured Test Transport Zone"
        transport_type: "{{item.transport_type}}"
        host_switch_name: "{{item.host_switch_name}}"
        state: "present"
      with_items:
        - "{{transportzones}}"

    - name: Create uplink profile
      nsxt_uplink_profiles:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{item.display_name}}"
        mtu: 1600
        teaming: "{{item.teaming}}"
        transport_vlan: "{{item.transport_vlan}}"
        state: "present"
      with_items:
        - "{{uplink_profiles}}"

    - name: Create transport node
      nsxt_transport_nodes:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.display_name}}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        transport_zone_endpoints: "{{item.transport_zone_endpoints}}"
        node_deployment_info: "{{item.node_deployment_info}}"
        state: present
      with_items:
        - "{{transport_nodes}}"
