# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: deploy NSX Manager OVA
      nsxt_deploy_ova:
        ovftool_path: "/usr/bin"
        folder: 'folder-os-datacenter'
        datacenter: "os-datacenter"
        datastore: "datastore"
        portgroup: "VM Network"
        cluster: "os-compute-cluster-1"
        vmname: "nsxt-manager"
        hostname: "nsxt-manager-10"
        dns_server: "10.161.244.213"
        dns_domain: "eng.vmware.com"
        ntp_server: "123.108.200.124"
        gateway: "10.112.203.253"
        ip_address: "10.112.201.24"
        netmask: "255.255.224.0"
        admin_password: "Admin!23Admin"
        cli_password: "Admin!23Admin"
        path_to_ova: "http://build-squid.eng.vmware.com/build/mts/release/bora-10566174/publish/nsx-unified-appliance/exports/ovf/"
        ova_file: "nsx-unified-appliance-2.4.0.0.0.10566180.ovf"
        vcenter: "10.92.114.248"
        vcenter_user: "administrator@vsphere.local"
        vcenter_passwd: "Admin!23"
        deployment_size: "small"
        role: "nsx-manager nsx-controller"
